# Generated by Django 3.2.9 on 2021-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman'), ('child', 'child'), ('vagetable&fruits', 'vagetable&fruits')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
