# Generated by Django 3.2.9 on 2021-12-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0008_auto_20211202_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='prating',
        ),
    ]
